substitutions:
  _SHORT_SHA: ''
  _COMMIT_SHA: ''
  # Unity GCS Bucket: If set, Unity files will be loaded from GCS instead of local nginx
  # Example: _UNITY_GCS_BUCKET=metavr-unity-build-production
  _UNITY_GCS_BUCKET: ''
  # CDN IP: If set, nginx will use CDN URL instead of direct GCS (faster performance)
  # Example: _CDN_IP=34.102.136.180
  _CDN_IP: ''

steps:
  # Determine SHORT_SHA: use provided SHORT_SHA, or extract from COMMIT_SHA, or use BUILD_ID
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "📋 Step 1/5: Preparing Build Configuration"
        echo "=========================================="
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        
        if [ -n "$$_SHORT_SHA" ]; then
          TAG=$$_SHORT_SHA
          echo "✅ Using provided SHORT_SHA: $$TAG"
        elif [ -n "$$_COMMIT_SHA" ]; then
          TAG=$${_COMMIT_SHA:0:7}
          echo "✅ Extracted tag from COMMIT_SHA: $$TAG"
        else
          TAG=$${BUILD_ID:0:7}
          echo "✅ Using BUILD_ID as fallback: $$TAG"
        fi
        
        echo "📌 Final image tag: $$TAG"
        echo "$$TAG" > /workspace/image-tag.txt
        echo "✅ Configuration saved"
        echo ""
    env:
      - '_SHORT_SHA=${_SHORT_SHA}'
      - '_COMMIT_SHA=${_COMMIT_SHA}'
      - 'BUILD_ID=${BUILD_ID}'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "=========================================="
        echo "🔨 Step 2/5: Building Docker Image"
        echo "=========================================="
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        
        TAG=$$(cat /workspace/image-tag.txt)
        IMAGE_TAG=gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG
        IMAGE_LATEST=gcr.io/$$PROJECT_ID/metavr-frontend:latest
        
        echo "📦 Building image: $$IMAGE_TAG"
        echo "📦 Also tagging as: $$IMAGE_LATEST"
        echo "⏳ This may take a few minutes..."
        echo ""
        echo "📁 Current directory: $$(pwd)"
        echo "📁 Listing files:"
        ls -la | head -20
        echo ""
        echo "📁 Checking vite-project:"
        ls -la vite-project/ | head -10 || echo "vite-project not found!"
        echo ""
        
        if [ ! -f "vite-project/Dockerfile.prod" ]; then
          echo "❌ ERROR: Dockerfile.prod not found!"
          echo "Looking for: vite-project/Dockerfile.prod"
          find . -name "Dockerfile.prod" 2>/dev/null || echo "Dockerfile.prod not found anywhere!"
          exit 1
        fi
        
        echo "✅ Dockerfile.prod found, starting build..."
        docker build \
          -t $$IMAGE_TAG \
          -t $$IMAGE_LATEST \
          -f vite-project/Dockerfile.prod \
          vite-project
        
        echo ""
        echo "✅ Docker image built successfully!"
        echo "📦 Image: $$IMAGE_TAG"
        echo "📦 Verifying image exists..."
        docker images | grep metavr-frontend || echo "⚠️ Image not found in local registry"
        echo ""
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_UNITY_GCS_BUCKET=${_UNITY_GCS_BUCKET}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "📤 Step 3/5: Pushing Docker Image (Tagged)"
        echo "=========================================="
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        
        TAG=$$(cat /workspace/image-tag.txt)
        IMAGE_TAG=gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG
        
        echo "📤 Pushing: $$IMAGE_TAG"
        echo "⏳ Uploading to Container Registry..."
        echo ""
        
        docker push $$IMAGE_TAG
        
        echo ""
        echo "✅ Image pushed successfully!"
        echo ""
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_UNITY_GCS_BUCKET=${_UNITY_GCS_BUCKET}'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "📤 Step 4/5: Pushing Docker Image (Latest)"
        echo "=========================================="
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        
        IMAGE_LATEST=gcr.io/$$PROJECT_ID/metavr-frontend:latest
        
        echo "📤 Pushing: $$IMAGE_LATEST"
        echo "⏳ Uploading to Container Registry..."
        echo ""
        
        docker push $$IMAGE_LATEST
        
        echo ""
        echo "✅ Latest image pushed successfully!"
        echo ""
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_UNITY_GCS_BUCKET=${_UNITY_GCS_BUCKET}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "🚀 Step 5/5: Deploying to Cloud Run"
        echo "=========================================="
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        
        TAG=$$(cat /workspace/image-tag.txt)
        IMAGE_TAG=gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG
        
        echo "🌍 Service: metavr-frontend"
        echo "📍 Region: us-central1"
        echo "📦 Image: $$IMAGE_TAG"
        echo "💾 Memory: 512Mi"
        echo "⚡ CPU: 1"
        echo "⏳ Deploying..."
        echo ""
        
        # Set environment variables for Cloud Run
        # VITE_UNITY_GCS_BUCKET: If set, Unity files will be loaded from GCS instead of local nginx
        # CDN_IP: If set, nginx will use CDN URL for faster performance
        ENV_VARS=""
        if [ -n "$${_UNITY_GCS_BUCKET}" ]; then
          ENV_VARS="--set-env-vars VITE_UNITY_GCS_BUCKET=$${_UNITY_GCS_BUCKET}"
          echo "📦 Using GCS bucket: $${_UNITY_GCS_BUCKET}"
        else
          echo "📦 Using local Unity files (nginx)"
        fi
        
        # Add CDN IP if available (for nginx proxy_pass optimization)
        if [ -n "$${_CDN_IP}" ]; then
          if [ -n "$$ENV_VARS" ]; then
            ENV_VARS="$$ENV_VARS,CDN_IP=$${_CDN_IP}"
          else
            ENV_VARS="--set-env-vars CDN_IP=$${_CDN_IP}"
          fi
          echo "🌐 Using CDN IP: $${_CDN_IP} (faster performance)"
        else
          echo "📦 Using direct GCS proxy (CDN not configured)"
        fi
        echo ""
        
        SERVICE_URL=$$(gcloud run deploy metavr-frontend \
          --image $$IMAGE_TAG \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 300 \
          $$ENV_VARS \
          --format="value(status.url)") && \
        echo "" && \
        echo "Setting IAM policy for public access..." && \
        gcloud run services add-iam-policy-binding metavr-frontend \
          --region us-central1 \
          --member=allUsers \
          --role=roles/run.invoker \
          --quiet || echo "IAM policy may already be set" && \
        echo "" && \
        echo "==========================================" && \
        echo "🔍 Health Check: Testing Unity NPC Page" && \
        echo "==========================================" && \
        echo "Service URL: $$SERVICE_URL" && \
        echo "Testing Unity NPC page: $$SERVICE_URL/unity/npc/index.html" && \
        echo "Waiting 10 seconds for service to be ready..." && \
        sleep 10 && \
        HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$$SERVICE_URL/unity/npc/index.html") && \
        echo "HTTP Status Code: $$HTTP_CODE" && \
        if [ "$$HTTP_CODE" = "200" ]; then \
          echo "✅ Unity NPC page is accessible (200 OK)"; \
        elif [ "$$HTTP_CODE" = "404" ]; then \
          echo "❌ ERROR: Unity NPC page returned 404 Not Found!"; \
          echo "The deployment failed because the Unity NPC page is not accessible."; \
          echo "Please check the build logs for extraction issues."; \
          exit 1; \
        else \
          echo "⚠️ WARNING: Unity NPC page returned HTTP $$HTTP_CODE"; \
          echo "This may indicate an issue. Please verify manually."; \
        fi && \
        echo "" && \
        echo "==========================================" && \
        echo "✅ Deployment completed successfully!" && \
        echo "==========================================" && \
        echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')" && \
        echo ""
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_UNITY_GCS_BUCKET=${_UNITY_GCS_BUCKET}'

images:
  - 'gcr.io/$PROJECT_ID/metavr-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

