substitutions:
  _SHORT_SHA: '${SHORT_SHA}'
  _COMMIT_SHA: '${COMMIT_SHA}'

steps:
  # Determine SHORT_SHA: use provided SHORT_SHA, or extract from COMMIT_SHA, or use BUILD_ID
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "$$SHORT_SHA" ]; then
          TAG=$$SHORT_SHA
        elif [ -n "$$COMMIT_SHA" ]; then
          TAG=$${COMMIT_SHA:0:7}
        else
          TAG=$${BUILD_ID:0:7}
        fi
        echo "Using tag: $$TAG"
        echo "$$TAG" > /workspace/image-tag.txt
    env:
      - 'SHORT_SHA=${_SHORT_SHA}'
      - 'COMMIT_SHA=${_COMMIT_SHA}'
      - 'BUILD_ID=${BUILD_ID}'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$$(cat /workspace/image-tag.txt)
        docker build \
          -t gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG \
          -t gcr.io/$$PROJECT_ID/metavr-frontend:latest \
          -f vite-project/Dockerfile.prod \
          vite-project
    env:
      - 'PROJECT_ID=${PROJECT_ID}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$$(cat /workspace/image-tag.txt)
        docker push gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG
    env:
      - 'PROJECT_ID=${PROJECT_ID}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/metavr-frontend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$$(cat /workspace/image-tag.txt)
        gcloud run deploy metavr-frontend \
          --image gcr.io/$$PROJECT_ID/metavr-frontend:$$TAG \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 80 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 300
    env:
      - 'PROJECT_ID=${PROJECT_ID}'

images:
  - 'gcr.io/$PROJECT_ID/metavr-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

